### ISSUE TITLE
Dash examples documentation is lacking

### ISSUE THREAD

**Issue by SirVer** [predict-idlab/plotly-resampler#102]
So I want to use this wonderful library within my web application - I do not do jupyter notebooks, since most of my apps end up with the business site of our company in the end. I succeed in doing this with my data:

~~~
fig = FigureResampler(go.Figure())
fig.add_trace(go.Scattergl(name='noisy sine', showlegend=True), hf_x=x, hf_y=noisy_sin)

fig.show_dash(mode='inline')
~~~

The show_dash serves a webserver, and within it everything works great. However, I want to call `run_server` since I have other logic. However, whenever I do that, also adding callbacks or anything more complex, my traces stop autoupdating - only the initial subsampling works. Reading through `https://github.com/predict-idlab/plotly-resampler/tree/main/examples/dash_apps` leaves a lot more questions than answers.

- There are two different examples, it is unclear what they do - their in-code description do not help me. What folders of files? They do not run for me for their dependencies do not install on Mac OS (parquet, numpy among others are awful in virtualenvs). Also, they require parquet data that is not provided to run. Why are they not using synthetic data like the README? And if you need to use data, use compressed CSVs, not parquet files please. I should not need to know about parquet files to use this library, that is out of scope of a subsampling library.
- One of the apps [states that the FigureSampler](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/dash_app.py#L29) must live for the existence of the App. That is great to know, but should be in a document, not buried in code.
- The updating is very ominous. What does `[construct_update_data](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/dash_app_coarse_fine.py#L125)` do? [TraceUpdater](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/dash_app.py#L76) show up here and there and they sound like they are crucial. They are not explained though. The [corresponding website](https://github.com/predict-idlab/trace-updater) only states that TraceUpdater is tightly coupled to plotly-resampler - neither page explains what they are and how they are used. And how I would use them in my own code.

This seems such a great piece of software, at the current state I cannot make any use of it though. I am not a newbie (I have >20 years of OSS experience) and I really applied myself. I am confident if the examples would run I could figure out what I need to know, but they do not and I am at a loss. Please help me make use of your work and provide a tutorial or sample app that is truly simple and cuts out everything that is not necessary.

**Comment by jonasvdd** [comment]
Hi @SirVer, 

The dash-app examples will be improved in PR #104. 

If you want to provide more feedback; this is the branch: https://github.com/predict-idlab/plotly-resampler/tree/improve_docs/examples

**Comment by SirVer** [comment]
@jonasvdd Thanks for the link. I will review and leave feedback on the PR.

**Comment by jonasvdd** [comment]
As #104 is merged, I will close this issue! 😄
