### ISSUE TITLE
when install plotly-resampler Collecting lttbc==0.2.0 always fail 

### ISSUE THREAD

**Issue by clemente0420** [predict-idlab/plotly-resampler#108]
Collecting lttbc==0.2.0
  Downloading lttbc-0.2.0.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 kB 247.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j1wawuxs/lttbc_df1b4fc03c7946fd893244304b8faa7f/setup.py", line 7, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by clemente0420** [comment]
using normal-way setup.py may be better, not using subprocess install

**Comment by jonasvdd** [comment]
Hi @clemente0420, can you try to install the plotly-resampler release candidate? https://pypi.org/project/plotly-resampler/0.8.0rc5/

In this version (see branch `improve_docs`), we added our [own derived LTTB implementation](https://github.com/predict-idlab/plotly-resampler/blob/fb8f42f28ae0ebdc67dcbe1081cedf23440f72ca/plotly_resampler/aggregation/algorithms/lttbcv2.c) instead of depending on lttbc.

**Comment by jvdd** [comment]
Hi @clemente0420,

I think this issue is related to #106

Does `pip install plotly-resampler==0.8.0rc5` work for you? (as in this pre-release we removed the lttbc dependency and included an adapted C implementation in this repo - see more in my answer to #106)

**Comment by jvdd** [comment]
Damn @jonasvdd beat me by 3 seconds :upside_down_face:

**Comment by jonasvdd** [comment]
🐎

**Comment by jonasvdd** [comment]
Hi @clemente0420

Did installing `plotly-resampler==0.8.0rc5` work for you?

**Comment by jonasvdd** [comment]
Hi @clemente0420,

Could you try `pip install plotly-resampler==0.8.0rc11` (skip the ones in between 🤡).

Kind regards,
Jonas

**Comment by thanosam** [comment]
Try to have preinstalled in your environment the numpy. You can do so in the setup.py file. This is how it worked for me so far (last plotly-resampler installed is 7.2.2)

**Comment by jonasvdd** [comment]
@thanosam @clemente0420,

Normally `plotly-resampler=0.8.0` resolves this numpy build requirement + uses faster (self written) LTTB c bindings. 🚀  additionally we also added more documentation about installation errors in the `FAQ` section of our docs.

Note: when the current C code building fails; there is a slower LTTB python fallback; so normally you should now always be able to install the package.
