### ISSUE TITLE
Loosen up plotly dependencies

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#113]
see: https://github.com/pycaret/pycaret/pull/2866

**Comment by jonasvdd** [comment]
see: https://lgtm.com/projects/g/predict-idlab/plotly-resampler/?mode=list

**Comment by sriveravi** [comment]
Plotly-resampler looks very promising but I couldn't get it to work in my setup. Seems like the dependency conflicts are a bit rough right now but they are actively working on it. 

I got it to install on a fresh virtualenv, but things got pretty angry
