### ISSUE TITLE
pandas plotting back-end = "plotly" (and `register_plotly_resampler`) + datetime index working really slow

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#120]

**Comment by jvdd** [comment]
Are we sure that this is fixed? @jonasvdd

**Comment by jvdd** [comment]
Just double checked this - is still significantly slower than numerical index (1.5s vs 4.2s) - but this is certainly a lot faster than it originally was (thx to PR #116)

Will close this for now - feel free to re-open or further comment if anyone thinks this is still a (big) problem.

**Comment by jonasvdd** [comment]
Big thanks for verifying this @jvdd! 🤗
