### ISSUE TITLE
`max_n_samples` in add trace(s) seems to do nothing with `plotly-resampler=0.8.1`

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#124]
I was able to pinpoint the issue, and it seems that this line within `AbstractFigureResampler` causes the issue:

```python
super(self._figure_class, self).add_trace(trace, **trace_kwargs)
```
Which calls the `BaseTraceDatatype` its `add_trace` method, which on its end:
![image](https://user-images.githubusercontent.com/38005924/196756520-6cfd80b5-abe2-42b6-ad93-ba72d20bdaa5.png)

calls `self.add_trace` (bringing us back to the `AbastractFigureResampler` class, and as a result, the trace will be aggregated.

**Comment by jvdd** [comment]
Solved in #127
