### ISSUE TITLE
Make the `features` dropdown in `readme.md` more "visible"

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#136]
As for now the `features` dropdown is a tad to blend. 

Aditionally:
- add the support for `dataspell`

**Comment by jvdd** [comment]
I'm for dropping the dropdown :sweat_smile: 
Why?
- Features is currently below Usage & Installation section (so space is less "expensive" over there imo)

**Comment by jvdd** [comment]
Fixed in cc1f8f0d181696aef3b40d0ff6d551f9a14bf0e9 :handshake:
