### ISSUE TITLE
[BUG] resampling upper/first subplot when zooming in on lower, non-shared x-axes subplots

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#137]
## Minimal breaking example:
```python
import numpy as np
from plotly.subplots import make_subplots
from plotly_resampler import FigureResampler

arr = np.sin(np.arange(1_000_000) / 1000)
fr = FigureResampler(make_subplots(rows=3, shared_xaxes=False, vertical_spacing=0.05))
fr.add_trace({"name": "raw"}, hf_y=arr)
fr.add_trace({"name": "raw"}, hf_y=arr[::1500], row=2, col=1)
fr.add_trace({"name": "raw"}, hf_y=arr[::1500], row=3, col=1)
fr.show_dash(mode="inline", port=8050)
```

Zoom on middle lower plot
![image](https://user-images.githubusercontent.com/38005924/203113837-e1a67a3e-7193-4da9-ae04-0790ddacfe3e.png)
And you will get this:
![image](https://user-images.githubusercontent.com/38005924/203113996-fa527c8f-a1f9-450c-b8ae-894af431315b.png)

i.e., the upper plot is resampled to the same view as the lower one! 😮 

## The fix
change: 
https://github.com/predict-idlab/plotly-resampler/blob/b3f06fe32f6742dca63deb483d2568c2a668e0e9/plotly_resampler/figure_resampler/figure_resampler_interface.py#L402

to:
```python
                    y_axis = "y" 
```

---

## TODO

* failing test
   * fix code and make test work

**Comment by jvdd** [comment]
Closing this as fixed by #138
