### ISSUE TITLE
Python 3.11 not supported

### ISSUE THREAD

**Issue by ekreate** [predict-idlab/plotly-resampler#149]
Hi, I've tired to run the "working examples" in Python3.11 and get the following error:
![image](https://user-images.githubusercontent.com/30499201/208606304-73c0e202-4046-4b07-a67e-20592fe50f16.png)
When running the same example in Python3.9, it works fine.
really cool package! thx for all the support!

**Comment by jvdd** [comment]
Hi @ekreate! 
Thx for pointing this out, I'll try to reproduce this behavior myself.

Some additional questions;
- did you install plotly-resampler using `pip install`?
- what version of plotly-resampler did you install? (might perhaps be different for the 2 Python envs)
- do other imports work? (e.g., `from plotly_resampler import FigureResampler`)

Cheers, Jeroen

**Comment by jvdd** [comment]
Just checked the `pyproject.toml` and noticed that we do not support Python 3.11 yet! 

https://github.com/predict-idlab/plotly-resampler/blob/46499efdaa04e97ddaee9fa84d518087e6579b9c/pyproject.toml#L22

Guess your issue will narrow down to relaxing this.

**Comment by ekreate** [comment]
great, thx!

**Comment by jvdd** [comment]
Hey @ekreate,

I created [a release candidate](https://pypi.org/project/plotly-resampler/0.8.4rc1/) that contains the fixes from #150 

```bash
pip install plotly-resampler==0.8.4rc1
```

Can you install this version in Python 3.11 environment and confirm whether this issue is now resolved?

**Comment by jvdd** [comment]
Created a Python 3.11 env locally and this release candidate seems to work just fine :tada: 

PS: I susepect you installed v0.2.4 of plotly-resampler in your Python 3.11 env (as this version did not yet contain an upper limit of the supported Python version). However the `register_plotly_resampler` functionality was only [introduced in v0.7](https://github.com/predict-idlab/plotly-resampler/releases/tag/v0.7.0), which explains why you (i) managed to install plotly-resampler in Python 3.11, and (ii) why `register_plotly_resampler` was not found.

**Comment by ekreate** [comment]
Hi, I'll be able to try it only on Monday, thx for the extremely quick response.
Happy holidays! 🎅🏼🎉

**Comment by jvdd** [comment]
Perfect, looking forward to hear from you! 
Enjoy the holidays :christmas_tree: :santa:

**Comment by ekreate** [comment]
works perfectly! thx a bunch :)
