### ISSUE TITLE
No Figure vs. No Resampling

### ISSUE THREAD

**Issue by WilliamJudge94** [predict-idlab/plotly-resampler#155]
I have been trying to use the plotly-resampler for about a week and have yet to get it working. I even downloaded the figurewidget_example.ipynb file and the same issue occurs. 

**Issue:**
Either jupyter does not display the plotly figure and only outputs some text
![image](https://user-images.githubusercontent.com/37912237/210408344-2897a421-278d-4d39-900b-b1f19d96d7ac.png)

Or I just figure.show() and the resampler does not actually work. It will display the image yet refuse to resample.
![image](https://user-images.githubusercontent.com/37912237/210408553-f924bb37-6c34-43e1-8a7c-ea4f909a9421.png)

Any information on how to fix this issue would be greatly appreciated.

**Comment by WilliamJudge94** [comment]
here is an export of my conda environment to reproduce this error

name: plotly_re
channels:
  - plotly
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=hafa529b_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=1.15.1=py38h74dc2b5_0
  - comm=0.1.2=pyhd8ed1ab_0
  - debugpy=1.6.4=py38hfa26641_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py38h7927eab_102
  - hdf5=1.12.2=nompi_h4df4325_101
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipykernel=6.19.4=pyh210e3f2_0
  - ipython=8.8.0=pyh41d4057_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.2=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.87.0=hdc1c0ab_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.51.0=hff17c54_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py38h7b6447c_1000
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.4.12=py38h06a4308_0
  - numexpr=2.8.3=py38h36ff5c2_101
  - numpy=1.24.1=py38hab0fcb9_0
  - openssl=3.0.7=h0b41bf4_1
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.5.2=py38h8f669ce_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly=5.11.0=py_0
  - plotly_express=0.4.1=py_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py38h0a891b7_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py38h1de0b5d_0
  - pytables=3.7.0=py38hf134f34_3
  - python=3.8.15=h4a9ceb5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytz=2022.7=pyhd8ed1ab_0
  - pyzmq=24.0.1=py38hfc09fa9_1
  - readline=8.1.2=h0f457ee_0
  - scipy=1.9.3=py38h8ce737c_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_2
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py38h26c90d9_2
  - tenacity=8.1.0=pyhd8ed1ab_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.6.0=py38h06a4308_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.2=py38h0a891b7_1
  - traitlets=5.8.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py38_1
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zstd=1.5.2=h6239696_4
  - pip:
    - ansi2html==1.8.0
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.3
    - dash==2.7.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask==2.1.3
    - flask-cors==3.0.10
    - idna==3.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jupyter-dash==0.4.2
    - orjson==3.8.3
    - plotly-resampler==0.8.3
    - requests==2.28.1
    - retrying==1.3.4
    - trace-updater==0.0.9
    - urllib3==1.26.13
    - werkzeug==2.1.2
prefix: /home/williamjudge/mambaforge/envs/plotly_re

**Comment by jonasvdd** [comment]
Hi @WilliamJudge94,

Happy new year! 🎉 

 `FigureWidgetResampler` outputs a (wrapped) [plotly.graph_objects.FigureWidget](https://plotly.com/python/figurewidget/). 

So my questions are
* Are you able to output a `FigureWidget` in your jupyter environment?
* Did you try any of the [other examples](https://github.com/predict-idlab/plotly-resampler/tree/main/examples) / dash apps<br>(or are you really interested in the `FigureWidgetResampler` use case)

Note that [FigureResampler](https://predict-idlab.github.io/plotly-resampler/figure_resampler.html#plotly_resampler.figure_resampler.FigureResampler) is also another option to create dynamically `plotly-resampler` figures. This mode does not utilize widgets, but spawns an (inline) dash app, which requires a network port.

Using the FigureWidgetResampler example with a FigureResampler, looks like this:
```python
from plotly_resampler import FigureResampler

# Wrap a figure with FigureResampler
fw_fig = FigureResampler(make_subplots(rows=2, shared_xaxes=False))

fw_fig.add_trace(go.Scattergl(), hf_x=x, hf_y=y * 1.000003**x, row=1, col=1)
fw_fig.add_trace(go.Scattergl(), hf_x=x, hf_y=(y + 3) * 0.999997**x, row=2, col=1)
fw_fig.update_layout(height=500, showlegend=True)

# Use the `show_dash` function to show the figure
# The "external" mode will open up a network port; i.e
# 127.0.0.01:<PORT>, in this case 127.0.0.1:8053
# or you can set the `mode` argument to inline to show
# the resampled figure in an iframe output
fw_fig.show_dash(mode='external',  port=8053
```

Looking forward to hearing back from you,
Kind Regards,
Jonas

**Comment by WilliamJudge94** [comment]
@jonasvdd 

Thank you so much for your help! I realized a large portion of my issue was related to dash since I am running the resampler on a remote server. Thank you so much for your help!!

**Comment by jonasvdd** [comment]
Hi @WilliamJudge94,

Glad to hear! 😄 

If your issue is resolved, could you close this thread?
