### ISSUE TITLE
Assertion Error without any explanation / why do x-values have to be unique? 

### ISSUE THREAD

**Issue by johann-petrak** [predict-idlab/plotly-resampler#158]
I am getting this error extremely frequently: 

```
783 hf_series = self._to_hf_series(x=dc.x, y=dc.y)
    785 # Checking this now avoids less interpretable `KeyError` when resampling
--> 786 assert hf_series.index.is_monotonic_increasing
    788 # As we support prefix-suffixing of downsampled data, we assure that
    789 # each trace has a name
    790 # https://github.com/plotly/plotly.py/blob/ce0ed07d872c487698bde9d52e1f1aadf17aa65f/packages/python/plotly/plotly/basedatatypes.py#L539
    791 # The link above indicates that the trace index is derived from `data`
    792 if trace.name is None:

AssertionError: 
```

This happens when adding a trace to a figure which has been wrapped in a FigureWidgetResampler

```
    fig.add_trace(
        go.Scattergl(
            x=dfp[xvar].values,
            y=dfp[yvar].values,
            name=var,
            yaxis="y2",    
            marker = dict(color = palette[idx])),
        #hf_x=dfp[xvar].values,
        #hf_y=dfp[yvar].values,
        #max_n_samples=5000
    )
```

As it turns out the code seems to require that the x values are monotonically increasing, however for a pure Plotly scatter plot, this is not required. Why is it necessary here? 

However a proper error message, giving a clear explanation of what is necessary and why might be a better way to show this error (though not making this an error would be even better).

**Comment by jonasvdd** [comment]
Hi @johann-petrak, 

Thank you for creating these issues! 

> As it turns out the code seems to require that the x values are monotonically increasing, however for a pure Plotly scatter plot, this is not required. Why is it necessary here?

`Plotly-resampler` is built to create **scalable time series** visualizations, where time series are defined *a series of data points indexed in time order*.  The scalability is achieved through data [aggregation](https://github.com/predict-idlab/plotly-resampler/blob/main/plotly_resampler/aggregation/aggregators.py) algorithms, such as Largest Triangular Three Buckets (LTTB). These make the assumption that the data is sorted in time (i.e., `x`) dimension. For us, it also makes sense that the data-points are sorted in time.

I agree with you that the error message is not straightforward, and will try to tackle this in a future PR!

Could you provide to me any reason why you find this strange (except for the case that this isn't vanilla plotly behavior)?

Kind regards,
Jonas

**Comment by johann-petrak** [comment]
Sorry for the misunderstanding, I do not really find it strange, just surprising first (plot that works with plotly does not work when wrapped), then puzzling (empty assertion message, only able to derive what is going on from looking at the code). 
So I explicitly testing and throwing an Exception with a good error message will help with both of these. 

I also initially misunderstood the problem since I thought that strict monotonicity is required, but I believe only monotonicity is required?

**Comment by jonasvdd** [comment]
indeed! only monotonicity is required! :)

**Comment by jonasvdd** [comment]
I will check this somewhere later today @lamhoangtung, but almost 100% sure that the behavior you propose, works!

**Comment by jonasvdd** [comment]
Instead of using a single non-monotonic trace with the `fill='toself'`;
use two traces and the `fill='tonexty'` property.

Is i.m.o. even more clear to read.

```python
import pandas as pd; import numpy as np
import plotly.graph_objects as go
from plotly_resampler import FigureResampler

# Construct the data
n = 1_000_000
x = np.arange(n) + 1
y = np.sin(x / (n / 25))

# Construct the upper and lower bounds
upper = y + .5 + (y)**2 + np.random.randn(n) * 0.05
lower = np.min([y -.5, y - (abs(y)**.5 + np.random.randn(n) * 0.2)], axis=0)

# 0. Create the figure
fig = FigureResampler(go.Figure())

# 1.  add the traae
fig.add_trace(go.Scatter(
    x=x, y=y,
    line_color='rgb(0,100,80)',
    name='Fair',
))

# 2. add the bounds
# NOTE: we use two monotonic increasing traces to fill the area
fig.add_trace(go.Scatter(x=x, y=upper, line_width=0, showlegend=False))
fig.add_trace(go.Scatter(
    x=x,
    y=lower,
    fill='tonexty', # fill to the previous trace
    fillcolor='rgba(0,100,80,0.2)',
    showlegend=False,
    line_width=0,
))

# 3. show the figure
fig.show_dash(mode='inline')
```

![image](https://user-images.githubusercontent.com/38005924/212652314-3806dab2-70b4-49e2-a72c-721e1cf1b7de.png)

**Comment by lamhoangtung** [comment]
Thank you for the quick reply and the great workaround @jonasvdd :D

**Comment by jonasvdd** [comment]
Wrote a more clear assert message in #162 (@johann-petrak)
