### ISSUE TITLE
About plotly graph exporting to HTML file

### ISSUE THREAD

**Issue by buptycz** [predict-idlab/plotly-resampler#175]
In my case, I want to export my plotly graph into HTML for later use, and I just run the following code:

`fig.write_html('fig1.html', include_plotlyjs='cdn')`

The good news is I do get a complete figure with basic interactive features (zoom, hover, etc.), but it will lose the advanced features like **auto resampling** when you zoom in/out like in the jupyter. 

I've been looking for similar problems in every place, but I didn't think I find any direct detailed explanation and possible solution to this.

Maybe it's the innate html limitaiton, and hopefully someone can help me understand or even solve this.

**Comment by jonasvdd** [comment]
Hi @buptycz,

In the [`FAQ`](https://predict-idlab.github.io/plotly-resampler/FAQ.html) section of or docs, we have the subsection:
>  What is the difference between plotly-resampler figures and plain plotly figures?

The section explains that plotly-resampler achieves interactivity through callbacks that link the figure to a python back-end where the raw data resides. This means that dynamic resampling only works when there is a link between the figure and a python back-end. This link can be achieved through either a Dash app or IPYwidgets. 

Plotly's `fig.write_html` calls the [to_html](https://github.com/plotly/plotly.py/blob/5cdbc04a6f831b27058922a192a70e6e0af2500d/packages/python/plotly/plotly/io/_html.py#L27) function; which essentially dumps the back-end figure in a JSON and then writes it to an HTML file. This HTML file is no longer linked to the python back-end, and as a result will not serve the resampling functionaity.

I hope this information is helpful. Just as a side note, you could think of the `write_html` functionality as calling `.show()` on the figure, which returns a static HTML view.

**Comment by buptycz** [comment]
@jonasvdd Thanks for your timely reply! This explains a lot! 

But I still don't understand why auto-scale malfunctions either (works like reset axes), since it is not a data involved function as I see?

**Comment by jonasvdd** [comment]
A summary from [this post](https://community.plotly.com/t/plotly-html-file-autoscale-vs-reset-axes/66982):
-  `autoScale`: adjust the layout to fit all the data in the plot
-  `resetAxes`: uses the layout details that you've specified for the figure, potentially leaving some data out<br> (e.g., you've specified that y-axis range should be [0, 10], then applying `restAxes` will set the yaxis range to [0, 10], even when there are some datapoints outside this range)

When working with plotly-resampler figures, only data for the corresponding x-range is included in the plot. In contrast, non plotly-resampler figures include all data in the plot. This means that applying `autoScale` to plotly-resampler figures will only adjust the y-axis scale, while for normal plotly figures, it will fit both the x and y scales to the figure.

I recommend experimenting with plotly figures and adjusting the layout's axis range before plotting.

I suggest you play around with some plotly-figures and alter the `layout` its axis range before ploting.

**Comment by buptycz** [comment]
@jonasvdd  Thanks for your patient and elaborate explanation!

Now I know exactly the difference between them. And I agree the resampler way of autoscale is more intuive and handy, which is the very feature what I want in the **exported HTML file**.

But the problem is the exported HTML file will lose this feature too. And I thought this is should not be the same as the resampling case which caused by the raw data absence in the front end.  And as you said, 

> When working with plotly-resampler figures, only data for the corresponding x-range is included in the plot.

I think we just utilize the data already embedded for autoscale. But now I guess it's the **'link'** thing you said before.

Anyway, thanks for your time!
