### ISSUE TITLE
Flask version problems

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [predict-idlab/plotly-resampler#194]
It seems there is a problem when loading the package, It seems is related to the latest implementation of flask

the error comes from 
[plotly_resampler/figure_resampler/figure_resampler.py] 

`TypeError: __init__() got an unexpected keyword argument 'unbound_message'`

**Comment by jvdd** [comment]
Thx  for submitting this issue! I'll gladly look into it :) However this will require some more details.

Can you share some minimal reproducible code? @AndresOrtegaGuerrero

**Comment by AndresOrtegaGuerrero** [comment]
@jvdd  thank you!,

once i just want to import the library `from plotly_resampler.figure_resampler import FigureWidgetResampler`

I get these errors 

`Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?95b43a29-2779-4208-a29f-f308f1dcf0cf)---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/var/folders/j9/wdlj6wm955g56m71sbh6htfm0000gp/T/ipykernel_60215/2426789728.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/j9/wdlj6wm955g56m71sbh6htfm0000gp/T/ipykernel_60215/2426789728.py) in ()
      7 from aiidalab_widgets_base.viewers import StructureDataViewer
      8 from monty.json import jsanitize
----> 9 from plotly_resampler.figure_resampler import FigureWidgetResampler
     10 #import numpy as np

[~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/ogaa/Documents/~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/__init__.py) in 
      4 
      5 from .aggregation import LTTB, EfficientLTTB, EveryNthPoint
----> 6 from .figure_resampler import FigureResampler, FigureWidgetResampler
      7 from .registering import register_plotly_resampler, unregister_plotly_resampler
      8 

[~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/figure_resampler/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/ogaa/Documents/~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/figure_resampler/__init__.py) in 
     11 """
     12 
---> 13 from .figure_resampler import FigureResampler
     14 from .figurewidget_resampler import FigureWidgetResampler
     15 

[~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler.py](https://file+.vscode-resource.vscode-cdn.net/Users/ogaa/Documents/~/opt/anaconda3/envs/aiida2/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler.py) in 
     17 from typing import List, Tuple
     18 
...
---> 56 app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
     57     _cv_app, unbound_message=_no_app_msg
     58 )

TypeError: __init__() got an unexpected keyword argument 'unbound_message'`

regarding the libraries, I have used `Flask 2.2.2` and `2.2.3` , and `Werkzeug 2.2.3` `python 3.9.15`

**Comment by AndresOrtegaGuerrero** [comment]
I think the issue is my Werkzeug , i tried 2.2.2 no issue , I will close this issue

**Comment by jvdd** [comment]
Glad to see that the issue is resolved!

Also linking #128 & #123 here
