### ISSUE TITLE
Parrallelize the resampling

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#2]
- [x] How will the verbose-argument work then? 
-> maybe if verbose, set n_jobs to 0
- [x] use multiprocess to deal with local scope methods

**Comment by jonasvdd** [comment]
Current test with this showed that there is no significant added value when the data-aggregation in parallelized. @jvdd, can you elaborate on this?

**Comment by jayceslesar** [comment]
I guess a good example is

```py
import plotly.graph_objects as go
import numpy as np
from plotly_resampler import FigureResampler, FigureWidgetResampler


x = np.arange(1_000_000_000)
noisy_sin = (3 + np.sin(x / 200) + np.random.randn(len(x)) / 10) * x / 1_000

# OPTION 2 - FigureResampler: dynamic aggregation via a Dash web-app
fig = FigureResampler(go.Figure())
fig.add_trace(go.Scattergl(name='noisy sine0', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine1', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine2', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine3', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine4', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine5', showlegend=True), hf_x=x, hf_y=noisy_sin)
fig.add_trace(go.Scattergl(name='noisy sine6', showlegend=True), hf_x=x, hf_y=noisy_sin)

fig.show_dash(mode='inline')
```

**Comment by jonasvdd** [comment]
Hi @jayceslesar,

I think your quote does summarize this perfectly!
> There is definitely a point where those lines cross but what benefit is there is the real question.

This is one of the reasons that [this benchmarking repo](https://github.com/predict-idlab/plotly-resampler-benchmarks) arose. In [this readme](https://github.com/predict-idlab/plotly-resampler-benchmarks/blob/master/reports/README.md) you can see an elaboration of the graph I will drop below.

![image](https://user-images.githubusercontent.com/38005924/174541976-f13528fb-969a-48fa-83a0-2dae94418c40.png)

For the top right graph, even `Plotly-Resampler` its performance starts to drop (i.e., >5 seconds for more than 10 traces >50e6 data points). So there is certainly a point. 

When I played around with this, I saw that the multiprocessing logic gave an overhead of ~300ms. 

I think we should take both these cases into consideration when implemention the parallelization

**Comment by jonasvdd** [comment]
Resolved through integrating `tsdownsample` from `plotly-resampler>=0.9.0`

**Comment by jonasvdd** [comment]
https://github.com/predict-idlab/plotly-resampler/blob/0a68cb76e7893d19f0e5f252b81699b110f9638c/examples/dash_apps/02_minimal_cache.py#L53-L55

As shown in this example 🔝 , when you set the `parallel` argument to `True` parallelized resampling will be utilized. 

*Note*: vanilla parallelization is not possible with *LTTB*; which we explain in this [paper](https://arxiv.org/abs/2305.00332)
