### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#20]
Add more docs (+ examples) about:
- [x] How to integrate plotly-resampler with your custom dash app
- [x] Plotly-resampler & non hf-traces
- [x] Tips & tricks:
  * optimizing your code for faster figure construction
  * how to (not) add hf-traces and why you should do so
  * Aliasing
- [x] Position ploty-resampler to other tools (Plotjuggler, DataShader, (Holoviews), FigureWidgets + interaction ...)
    see [plotly-resampler benchmarks](https://github.com/predict-idlab/plotly-resampler-benchmarks)

**Comment by jvdd** [comment]
See #26

**Comment by jvdd** [comment]
Is now merged into the main branch!
v0.2.7 of this package contains these new features :smile: 

An example on how you can integrate into a custom dash app can be found under the `dash_apps` folder in [our examples](https://github.com/predict-idlab/plotly-resampler/tree/main/examples)

**Comment by prokie** [comment]
Thank you very much, I will start integrating it into my app today! 👍

**Comment by jonasvdd** [comment]
@prokie, were you able to integrate it in your app?

**Comment by prokie** [comment]
Yes, I also got the dynamic callbacks working. Great work!

**Comment by jonasvdd** [comment]
Glad to hear! :)
