### ISSUE TITLE
Non-index date time series as hf_x and pandas v2.0 compatibility

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#208]
- pandas version: `2.0.1`
- plotly_resampler version: `0.9.0rc1`

code snippet which fails
```python
import pandas as pd; import numpy as np
from plotly_resampler import FigureResampler

df = pd.DataFrame({'timestamp': pd.date_range('2020-01-01', '2020-01-02', freq='1s')})
df['value'] = np.random.randn(len(df))

fr = FigureResampler()
# This works
# fr.add_trace({}, hf_x=pd.Index(df.timestamp), hf_y=df.value)
# This doesn't
fr.add_trace({}, hf_x=df.timestamp, hf_y=df.value)
fr
```

### What causes the fail:
this line: https://github.com/predict-idlab/plotly-resampler/blob/e56cbc71d32991c68e5763d3652394aff83cf94a/plotly_resampler/figure_resampler/figure_resampler_interface.py#L787

Will give that the `datetime64` array requires a linear axis. As such, the `xaxis.range[0]` and `xaxis.range[1]` arguments will not be parsed to timestamps, and the hf_x slicing (i.e. the bisect), will fail, resulting in this error:
![image](https://github.com/predict-idlab/plotly-resampler/assets/38005924/914ceec8-3135-4fb3-bb6c-546053109c27)

### Solution

extend the check with:
```python
axis_type = (
    "date"
    if isinstance(dc.x, pd.DatetimeIndex) or
    pd.core.dtypes.common.is_datetime64_any_dtype(dc.x)
    else "linear"
)
```

### TODO:
- [x] verify if this occurs and works for pandas <2 <br>Indeed this, occurs aswell for pandas<2
- [x] create a PR and add tests for this.

**Comment by jvdd** [comment]
Done! [`plotly-resampler 0.9.0rc2`](https://pypi.org/project/plotly-resampler/0.9.0rc2/)
