### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'construct_update_data'

### ISSUE THREAD

**Issue by benmfox** [predict-idlab/plotly-resampler#215]
Hi! When I try to run the dash app example [02_minimal_cache.py](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/02_minimal_cache.py), I receive the following error after interacting with the plot (for example, zooming in) from the `update_fig` callback (which updates the trace-updater). 

```
AttributeError: 'dict' object has no attribute 'construct_update_data'
```

I believe this is because the plotly figure object has been serialized. Do these examples need to be updated to convert the dictionary back to a figure object or am I missing something here? 

I am using plotly-resampler==0.8.3.2, dash==2.9.3, and plotly==5.14.1.

**Comment by jvdd** [comment]
Hey @benmfox,

Thx for contributing this issue!

Have you tried `plotly-resampler==0.9.0rc3` (this is the latest pre-release version), also be aware that since 5 days our examples are slightly outdated due to the breaking changes in `dash-extensions` (see #214).

Cheers,
Jeroen

**Comment by benmfox** [comment]
Hi @jvdd,

Thanks for the quick response! Updating to `plotly-resampler==0.9.0rc3` and downgrading to `dash-extensions==0.1.13` worked!
