### ISSUE TITLE
`pip install plotly-resampler` download does not contain NoGapHandler

### ISSUE THREAD

**Issue by LeiRui** [predict-idlab/plotly-resampler#216]
1. pip install plotly-resampler
2. run demo `https://github.com/predict-idlab/plotly-resampler/blob/main/examples/basic_example.ipynb`
Error: cannot import NoGapHandler

**Comment by jvdd** [comment]
Hey @LeiRui 

We are working on releasing plotly-resampler 0.9.0 which contains several significant improvements.

We already updated the example notebooks for this release.

You can install the latest release candidate as stated here: https://pypi.org/project/plotly-resampler/0.9.0rc3/

Let us know if this resolves the issue.

Cheers,
Jeroen
