### ISSUE TITLE
Resample Older Data

### ISSUE THREAD

**Issue by firmai** [predict-idlab/plotly-resampler#222]
Thanks for the software, I want to resample older data, say 20 years, but want to keep latest data say 3 months in its daily format. This would be a great addition if it doesn't exist yet? Gives the benefit of both worlds. 

Let me know what I can do to implement this, I can work on it over the weekend.

Best,
Derek

**Comment by jonasvdd** [comment]
I will close this issue for now (as we got no response from @firmai).
