### ISSUE TITLE
Running in a Docker container - data is still resampled on zoom

### ISSUE THREAD

**Issue by zemmyang** [predict-idlab/plotly-resampler#230]
I have some code that plots PPG data, recorded at a rate of 75Hz over several hours (about 3M+ points). We need to be able to zoom in and see it at a scale of 5s.

We want it as a dash app on a server, so the testing is done on a docker container.

"overview":
![image](https://github.com/predict-idlab/plotly-resampler/assets/1752285/9420f2e0-3ede-4e28-b1f2-921d1617caec)

zoomed in:
![image](https://github.com/predict-idlab/plotly-resampler/assets/1752285/356880c6-b8b7-4103-8c60-6ef83756e168)

But the exact same code behaves as intended on a jupyter notebook:
![image](https://github.com/predict-idlab/plotly-resampler/assets/1752285/cda8fb96-3014-40fd-bdf7-37ae61a6811a)

Is there some option that's specific to the dash app? I'm not sure what I'm missing here.

Notes that might help:
- specifying `default_n_shown_samples` in `FigureResampler` does not seem to help. I get this error (Could not import lttbc; will use a (slower) python alternative.) on the jupyter notebook, but not on docker
- I'm using Scattergl
- relevant packages: dash==2.10.2, plotly_resampler==0.8.3.2, pandas==1.3.5, Flask==2.2.5

----

The Dockerfile:
```
FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install dash[diskcache]

COPY . .

RUN chmod u+x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
```

It's running as a Dash app with Flask, entrypoint.sh is just running the Flask stuff and then Flask sets up the Dash app. But running it as a solo Dash app gets me the same behavior

**Comment by jonasvdd** [comment]
@zemmyang,

I can see that you did not take a proper look at our [basic dash app example](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/01_minimal_global.py). 
We use dash callbacks, which leverage the `TraceUpdater` dash component to efficiently send the resampled data to the server. As in your app, no callbacks are listed at all, this will not resample. I suggest that you take a really close look at this example and aim to understand the inner workings. I think also the [documentation](https://predict-idlab.github.io/plotly-resampler/dash_app_integration.html) should help.

Additionally, passing your trace data to the `hf_x` and `hf_y` argument will speed up the `add_trace` method significantly.

*fyi*: also, if you want to support multiple sessions - you should take a look at [this example](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/dash_apps/03_minimal_cache_dynamic.py).

Hope this helps you any further,
Kind regards,
Jonas

**Comment by zemmyang** [comment]
ugh, sorry - the usage text in the readme made it sound like you just needed to replace Figure with FigureResampler. i feel like the page to the examples could be highlighted a bit more

anyway, it works now. i ran into other possible problems, but i think they're completely separate from this one.

thanks!
