### ISSUE TITLE
Saving plotly-resampler object for faster viewing

### ISSUE THREAD

**Issue by vinay-hebb** [predict-idlab/plotly-resampler#246]
I am plotting large time series array and it takes considerable time to plot. Currently, I am loading the data and passing it to resampler which resamples and plots. My understanding is that resampling code is taking time.

Is it possible to save the plotly resampler object (first time) so that I can load the object and view plot faster for future use?

**Comment by jvdd** [comment]
Hey @vinay-hebb,

Thx for submitting this issue. I observe the following questions in this issue;

A. Can you save plotly-resampler figures?
B. Can you view the plot faster?

---

## A. 

You can save Plotly-Resampler figures by serializing it.

```py
fig_to_save = ...  # some plotly-resampler figure

# Save the figure (pickle it)
pickle.dump(fig, open("saved_fig.pkl", "wb"))
del fig_to_save  # you can delete the plotly-resampler figure

# Load the figure
fig_loaded = pickle.load(open("saved_fig", "rb"))
```

## B.

Saving & loading should not result in faster downsample (as plotly-resampler is stateless).

Can you provide some more details;
- What is slow? The initial loading/rendering (i.e., the construction of your figure)?
  - How do you construct your plotly-resampler figure? (do you pass the `x` and `y` data as `hf_x` and `hf_y` to the `add_trace` method) - https://github.com/predict-idlab/plotly-resampler#usage
- What is the size of your data? (Number of signals, number of samples per signal)?

Feel free to submit some minimal working code on how you currently create your plots :)

---

Hope this answers your questions.

Cheers, Jeroen

**Comment by jonasvdd** [comment]
I will close this issue for now.
