### ISSUE TITLE
Difference between tsdownsample and resampler

### ISSUE THREAD

**Issue by firmai** [predict-idlab/plotly-resampler#247]
Just looking at the two projects https://github.com/predict-idlab/tsdownsample/ and  https://github.com/predict-idlab/plotly-resampler/

The documentation doesn't make the following very clear, why would one not just downsample and create a graphic versus using the resampler, is the resampler doing it dynamically so that everytime you filter the dataset it provides the n preselected samples thus maintaining high fidelity all the way down? 

Also if one doesn't select the number of samples, is there a good approximate default that kicks in for n selection? In the documentation it is hard for me to understand what the default behaviour is, how many n is being selected and what algo, is it LTTB?

And thanks for the software! 

Best,
Derek

**Comment by jonasvdd** [comment]
Hi @firmai,

I totally agree that we could make a larger effort to describe more of the inner workings of plotly-resampler (in the online docs) and its default settings.

However, I suggest, if time permits, that you can also skim these papers:
- plotly-resampler: https://arxiv.org/pdf/2206.08703.pdf (describes how plotly-resampler works and its advantages over other tools)
- tsdownsample: https://arxiv.org/pdf/2307.05389.pdf (describes what tsdownsample is, and some architectural choices)

> Q: why would one not just downsample and create a graphic versus using the resampler, is the resampler doing it dynamically so that everytime you filter the dataset it provides the n preselected samples thus maintaining high fidelity all the way down?

**A:** It is exactly what you think it is! :) `plotly-resampler` uses *user-graph-interaction callbacks* to resampler (i.e. perform time series data aggregation) for the interacted regions. (see 📷 ⬇️  - from the plotly-resampler paper)
![image](https://github.com/predict-idlab/plotly-resampler/assets/38005924/251455cc-2d02-491d-bb88-d7a5310091a5)

> Q: Also if one doesn't select the number of samples, is there a good approximate default that kicks in for n selection? In the documentation it is hard for me to understand what the default behaviour is, how many n is being selected and what algo, is it LTTB?

**A**: excellent question! We investigated these variables in this paper (https://arxiv.org/pdf/2304.00900.pdf). The default aggregator is [MinMaxLTTB](https://arxiv.org/pdf/2305.00332.pdf), you can think of it as a parallelizible variant of LTTB. The default number of selected samples for each aggregation $n_{out}$ is set to 1000. However, it highly depends on (i) browser zoom level, (ii) canvas width, and (iii) line width, which $n_{out}$ is optimal. As the latter requires a lot of back-end and front-end logic, we have not (yet) put this on our roadmap to implement an *automatic* $n_{out}$ mode.

Clarifies some stuff!
And of course, thank you for taking a great interest in our research/software!

Kind regards,
Jonas
