### ISSUE TITLE
[BUG] FigureResampler, FigureWidgetResampler, and register_plotly_resampler do not work for box traces

### ISSUE THREAD

**Issue by joshua-xia** [predict-idlab/plotly-resampler#249]
My original figure is about 20MB, I try the three methods in dash callback to return the figure to web frontend, but it seems the figure is not compressed

code as the following:

@callback(
    Output("dd-figure-container", "children"),
    Input("demo-dropdown", "value"),
    State("sessionStore", "data"),
)
def update_output(value, sessionID):
    data = query_data(sessionID)
    fig = plot_box(data, value)

    return dcc.Graph(figure=fig)

register_plotly_resampler(mode='auto')

def plot_box(data, select_column):
    fig = FigureWidgetResampler(go.Figure())
    fig.add_trace(
        go.Box(
            x=data[select_column],
            y=data.iloc[:, 1],
            boxpoints="outliers",
        )
    )

    return fig

the data is same

**Comment by jonasvdd** [comment]
@joshua-xia,

In order to create dash-app's it is considered best practice to use the plain `FigureResampler` class instead of using the `register_plotly_resampler` method.

I suggest you take a look at our
- dash app [docs](https://predict-idlab.github.io/plotly-resampler/v0.9.1/dash_app_integration/)
- dash app [examples](https://github.com/predict-idlab/plotly-resampler/tree/main/examples#2-dash-apps)

Hope this helps you further,
Jonas

**Comment by jonasvdd** [comment]
@joshua-xia,

My bad, I looked over the line that you use `go.Box` in your example. 
Indeed, plotly-resampler only supports the aggregation of `scatter[gl]` traces; as outlined #229 

Some references: 
possible workaround: https://stackoverflow.com/questions/54128082/how-to-plot-a-boxplot-using-aggregates-in-plotly
reason why box-plot sends all data to js: https://github.com/plotly/plotly.py/issues/2456

**Comment by joshua-xia** [comment]
> @joshua-xia,
> 
> My bad, I looked over the line that you use `go.Box` in your example. Indeed, plotly-resampler only supports the aggregation of `scatter[gl]` traces; as outlined #229
> 
> Some references: possible workaround: https://stackoverflow.com/questions/54128082/how-to-plot-a-boxplot-using-aggregates-in-plotly reason why box-plot sends all data to js: [plotly/plotly.py#2456](https://github.com/plotly/plotly.py/issues/2456)

I got it and close this issue, Thanks!

**Comment by joshua-xia** [comment]
closed
