### ISSUE TITLE
Could not install plotly-resampler library

### ISSUE THREAD

**Issue by maya2594** [predict-idlab/plotly-resampler#256]
Hi,

I am trying to install the plotly-resampler library wih python version 3.10. I also tried to install lower versions of this library (plotly-resampler==0.8.1) but couldn't work. But one of the dependency of plotly-resampler creating problwm or restructing it to install. getting following user warning: 

```
UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")

then error:  from plotly_resampler.aggregation import MedDiffGapHandler ImportError: cannot import name 'MedDiffGapHandler' from 'plotly_resampler.aggregation'

```
Could someone help me to install this library. Its bit urgent for me to use this library as because of this, i am not able to deploy my code in production.

Thanks!

**Comment by jonasvdd** [comment]
Hi @maya2594,

We removed the lttbc from `plotly-resampler>=0.9.0`.

Regarding the `MedDiffGapHandler` - as we made breaking changes in `plotly-resampler>=0.9.0` (i.e. moved around and renamed some of the aggregation interface code), we believe that your encountered issue stems from this.

I suggest that you, for now, lock `plotly-resampler` to `0.9.1`, try to get your code working locally, and then focus on deployment.

**Comment by maya2594** [comment]
Thanks for your response @jonasvdd :)
With this version, I hope MedDiffGapHandler will also works fine or?
I am using MedDiffGapHandler like this below, Is there any alternative to MedDiffGapHandler which functions same in plotly to fill_value=0,

`fig.add_trace(go.Scatter(name='Data', showlegend=True,line_shape='hv'), hf_x=plotdata['timestamp'], hf_y=plotdata['value'],gap_handler=MedDiffGapHandler(fill_value=0))`

Thanks!

**Comment by jonasvdd** [comment]
@maya2594,

The `MedDiffGapHandler` will work for `plotly-resampler>=0.9.0`. So it should work for `0.9.1` :) 

Kind regards,
Jonas

**Comment by maya2594** [comment]
@jonasvdd thanks, that works perfectly now :)
