### ISSUE TITLE
Seeing a `FutureWarning` for `.is_datetime64tz_dtype` from `figure_resampler_interface`

### ISSUE THREAD

**Issue by darynwhite** [predict-idlab/plotly-resampler#263]
https://github.com/predict-idlab/plotly-resampler/blob/03bb331ec5d03862951caeef87de3263690bb934/plotly_resampler/figure_resampler/figure_resampler_interface.py#L328

The line above is referenced when I generate a plot a resampler figure in a iPython Notebook, here is the error output:
```sh
lib/python3.11/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py:327:
FutureWarning:

is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
```

I'm running the latest release, 0.9.1

**Comment by jonasvdd** [comment]
Hi @darynwhite,

Thanks for reporting this issue, it can easily be fixed. 
I will look into it today!

I expect to create a new release somewhere later this week.

*p.s.*: This release will include some new features, such as a rangeslider 🔥 (see 📷 ⬇️ )

![Peek 2023-10-25 01-51](https://github.com/predict-idlab/plotly-resampler/assets/38005924/fbe9e83e-f2a7-4296-992e-2661e47a7915)

**Comment by jonasvdd** [comment]
PR is merged! :)

**Comment by darynwhite** [comment]
Is there going to be a release including this fix (and the other updates) or will I need to build this locally to test?

Thanks!

**Comment by jonasvdd** [comment]
If all goes well, we will create a new release candidate tomorrow! :)

**Comment by jonasvdd** [comment]
There is one more test that is failing, as I am now on holidy I will look into this somewhere later this week! 😄
