### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by jvdd** [predict-idlab/plotly-resampler#274]

**Comment by kb-** [comment]
Plotly-resampler installation works on Python 3.12 with the current tsdownsample version from the repo (since closing https://github.com/predict-idlab/tsdownsample/issues/61). 
However it doesn't work with tsdownsample = "0.1.2" specified in plotly-resampler's pyproject.toml

**Comment by Jamesong7822** [comment]
Any updates on this?

**Comment by Jamesong7822** [comment]
Excellent work @jonasvdd, i was like seeing this issue got merged so I thought the release was already supported as the README had the 3.12 support label as well
