### ISSUE TITLE
[FEAT] Support Numpy float 16

### ISSUE THREAD

**Issue by juliuslipp** [predict-idlab/plotly-resampler#298]
Hey guys,

any plans to support the numpy float16 datatype?

**Comment by jonasvdd** [comment]
Hey 👋🏼 ,

Could you specify which problems you exactly have with the float16 data type?
(As float16 as (`hf_`)`y` datatype works perfectly) 

Kind regards, 
Jonas

**Comment by juliuslipp** [comment]
Hey @jonasvdd, sorry for whatever reason this meant to be in another repository...

**Comment by jonasvdd** [comment]
No problem! Thank you for the swift reply! Have a good one :)
