### ISSUE TITLE
[BUG] `renderer="png"` - rendering png images in notebooks - does not work

### ISSUE THREAD

**Issue by etiennedemontalivet** [predict-idlab/plotly-resampler#302]
I am trying to replicate some of the [basic examples](https://github.com/predict-idlab/plotly-resampler/blob/main/examples/basic_example.ipynb). Especially, I'd like to produce some *png* figures when I share notebooks with others, but when I use `fig.show(renderer="png")`, it never returns anything (I waited for up to 20 minutes). 

If I use `USE_PNG = False`, the code works as expected and is super fast.

Here is the code I use:
``` python
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly_resampler import register_plotly_resampler, unregister_plotly_resampler

USE_PNG = True  # Set to false to use dynamic plots

n = 20000
x = np.arange(n)
x_time = pd.date_range("2020-01-01", freq="1s", periods=len(x))
noisy_sine = (3 + np.sin(x / 2000) + np.random.randn(n) / 10) * x / (n / 4)

register_plotly_resampler(mode="auto", default_n_shown_samples=4500)

fig = go.Figure()
fig.add_traces(
    [
        {"y": noisy_sine + 2, "name": "yp2", "type": "scattergl"},
        {"y": noisy_sine - 3, "name": "ym1", "type": "scatter"},
    ]
)

if USE_PNG:
    unregister_plotly_resampler()
    go.Figure(fig).show(renderer="png")
else:
    fig.show()
```

**Environment information**:
- OS: Windows 11
- Python environment: 
  - Python version: 3.9.12
   - plotly-resampler environment: I tried in VSCode 1.87.1, Jupyter Notebook 6.4.12 and JupyterLab '4.1.0'. Same behavior (never returns)
   - plotly-resampler version: '0.9.2'
   - kaleido: '0.2.1'
   - ipywidgets: '8.1.1'
 
Am I doing something wrong ?
Any help would be much appreciated!

**Comment by jonasvdd** [comment]
Hi @etiennedemontalivet,

I tried to reproduce your issue, but was not able to achieve your outcome. The screenshot below demonstrates both approaches I tried (on the 0.9.2. tag of plotly resampler in vscode, and creating a new python 3.10 virtualenv in which I install `kaleido`, `plotly-resampler`, `jupyter`, and `ipykernel`.

![image](https://github.com/predict-idlab/plotly-resampler/assets/38005924/bdb841da-03ff-4858-858b-eb9cbcce9685)

As I could not reproduce your error I hope that my tests may help you further with resolving it!
And please let me know when you've found the cause of your issue.

Kind regards,
Jonas

**Comment by etiennedemontalivet** [comment]
Thanks for your quick answer, I'll investigate in more details tomorrow and let you know.

**Comment by etiennedemontalivet** [comment]
Hi @jonasvdd , I investigated in multiple clean environments but sill have the issue... Here is what I tried:

<details>
  <summary>conda-based environment with python 3.10</summary> 

  ![resampler_issue0](https://github.com/predict-idlab/plotly-resampler/assets/7569375/f747c1f6-7a5b-4204-99e6-341628badbc2)
  ![resampler_issue1](https://github.com/predict-idlab/plotly-resampler/assets/7569375/ef0fbc01-d3d6-4f34-8645-99985bfa45de)
</details>

<details>
  <summary>Then I updated the <i>plotly-resampler</i> to get the latset version 0.9.2 </summary> 

  ![resampler_issue2](https://github.com/predict-idlab/plotly-resampler/assets/7569375/ab09af8d-2147-46e0-b1d3-f94fc96d4554)
  ![resampler_issue3](https://github.com/predict-idlab/plotly-resampler/assets/7569375/b4a907ec-58b5-44f0-84fe-05b4e98a5a66)
</details>

<details>
  <summary>Then I tried in an environment created with <i>python venv</i> and install the 4 packages with <i>pip install</i></summary> 
  ![resampler_issue4](https://github.com/predict-idlab/plotly-resampler/assets/7569375/548d62b6-80fb-489a-a7c2-519bd3f6f4f2)
  ![resampler_issue5](https://github.com/predict-idlab/plotly-resampler/assets/7569375/d8cacb47-7372-4542-b140-8d55174fe864)
</details>

<details>
  <summary>Lastly I tried in <i>jupyter notebook</i> with the 4 packages matching the versions of your screenshot</summary> 
  ![resampler_issue6](https://github.com/predict-idlab/plotly-resampler/assets/7569375/4f5f436f-6ea0-4c1c-9891-b6b864609b2c)
</details>

Can you please tell me what `plotly` version you're using ?  
Do you have any idea what might cause the bug on my side ?
Best,

**Comment by etiennedemontalivet** [comment]
The bug was coming from `kaleido`.
They have many open issues such as [this one](https://github.com/plotly/Kaleido/issues/164) or [this one](https://github.com/plotly/Kaleido/issues/170).
At the end, reverting kaleido to version `0.1.0.post1` fixed my issue: 

``` bash
pip install "kaleido==0.1.0.post1"
```

Everything from `plotly-resampler` works now as expected.
Thanks for the support @jonasvdd !
