### ISSUE TITLE
[IMPROVEMENT] Add dash app title

### ISSUE THREAD

**Issue by Olivier0330** [predict-idlab/plotly-resampler#311]
Not really a bug, but more of an improvement suggestion.

The tab title of the Dash app will by default always be called 'Dash'. 
![image](https://github.com/user-attachments/assets/ab59c138-0c8d-47a8-bfc6-830d7056af02)

However, when plotting multiple data sets in different tabs, it would be useful to assign a name to the tab to know which data is shown in which tab (for example when files are plotted). 
![image](https://github.com/user-attachments/assets/250d69a0-f6b0-44bf-94a0-e69a994b87e0)

This can be done by adding a 'title' argument in the show_dash function of the FigureResampler class and assigning 'app.title' 
![image](https://github.com/user-attachments/assets/71df69fc-64ee-4bb0-92af-f4f1b856fc1c)

**Comment by jonasvdd** [comment]
@Olivier0330
If you use the manual mode, you are able to specify the title in the `init_dash_kwars` argument; see ⬇️ 

```python
from plotly_resampler import FigureResampler
import plotly.graph_objects as go

fig = FigureResampler(go.Figure())
fig.show_dash(mode='external', port=8012, init_dash_kwargs={'title': 'TEST TITLE'})
```

---

![image](https://github.com/user-attachments/assets/20eca9ab-51b9-42e8-85c6-1d9d8edd8c54)

I will close this issue for now.
Kind regards,
Jonas
