### ISSUE TITLE
Inconsistent behavior of `show` method

### ISSUE THREAD

**Issue by emield12** [predict-idlab/plotly-resampler#40]
Currently, when you call the `show` method on a FigureResampler object it returns a down sampled version of the figure that does not resample, which looks like a "broken" figure when zooming in. This behavior is inconsistent with standard Plotly figures and could create confusion.
I see two possible solutions to solve this problem:
- Making the behavior consistent with Plotly by returning the original (not down sampled) figure when `show` is called.  Although this could be annoying if you are working with a lot of points and inadvertently call show and crash your kernel/browser as a result.
- Keep the same behavior as now, but throw a warning message. As this might not result in the expected behavior.

**Comment by jonasvdd** [comment]
I indeed would opt for the second option, mainly due to the disadvantages of the first option, what do you think @jvdd?

**Comment by jonasvdd** [comment]
Maybe this can also be handled within #104

**Comment by jonasvdd** [comment]
Documented in FAQ section of #104
