### ISSUE TITLE
LTTB - 0.2.1 not working

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#42]
![image](https://user-images.githubusercontent.com/38005924/161756884-0c97f55a-92c6-4e61-aedc-e8f27d192d79.png)

TODO:
- [ ] Look into using other, (more optimized) LTTB versions, such as @mcourteaux its awesome [lttb](https://github.com/mcourteaux/fast-lttb) implementation

**Comment by jvdd** [comment]
Closing this as we now have our own lttb implementation in this repo (#103)
