### ISSUE TITLE
Problem with pyinstaller

### ISSUE THREAD

**Issue by Piotrkow** [predict-idlab/plotly-resampler#44]
Hi,

First thing - thanks for your work 👍 This Plotly-Resampler allow me to handle 30bln datapoints plots. Really great job!
Unfortunately I have a problem with your library combined with PyInstaller. Code works properly inside PyCharm but when I add to the code "from plotly_resampler import FigureResampler", build standalone .exe file and run it then it crash without any error.
Do you know what can be a root-cause or how can I WA this issue?
Ofc I added all needed dependencies to the *.spec file.

Update: when I removed Jupyter and show_dash() function then .exe file starts working so maybe there is some routing conflict between two local servers?
![Plotly-Resampler](https://user-images.githubusercontent.com/11377268/164914046-c5eca5f8-4525-4aac-a600-a5920ada83f5.PNG)

Thanks,
Piotr

**Comment by jvdd** [comment]
Hi @Piotrkow 

Were you able to resolve this issue, or found out some more information about the crash?

I have no experience with PyInstaller. So this answer might not be useful at all. But here are my 2 cents;
* plotly-resampler its dependencies are managed by [Poetry](https://python-poetry.org/), installing the files locally can be done by calling `poetry install` (this is for example used in the CI-CD testing). Perhaps it might be something to do with that?
* one other possibility could be that an .exe has perhaps no rights to start an application on a port (which happens once `.show_dash` is called)

Cheers,
Jeroen

**Comment by jonasvdd** [comment]
Hi @Piotrkow, any update on this issue?

**Comment by jvdd** [comment]
Ping @Piotrkow? :angel:

**Comment by jonasvdd** [comment]
@Piotrkow, will close this issue for now as we did not get an update.
