### ISSUE TITLE
Double Clicking on Dash App Does not Reset Axes

### ISSUE THREAD

**Issue by jayceslesar** [predict-idlab/plotly-resampler#49]

**Comment by jvdd** [comment]
Hi @jayceslesar

Indeed, double-clicking results does not Reset Axes as it results in an “Autoscale” event. @jonasvdd  & I decided to implement an Autoscale event as updating your y-range such that it shows all the data that is in your x-range. 

**Note:** vanilla Plotly figures their Autoscale result in Reset Axes behavior, in our opinion this did not make a lot of sense. It is therefore that we have overriden this behavior in `plotly-resampler`.

I'm interested in hearing your opinion about this!

Cheers, Jeroen

**Comment by jayceslesar** [comment]
This does make sense, looking at grafana's implementation of this feature, when zooming in on some data and then double-clicking it only zooms out on the set of points within your x-range. Maybe would want to add some functionality to do this where a developer could explicitly set this in place?

**Comment by jonasvdd** [comment]
Documented in #104

**Comment by quantlord8** [comment]
I'd like to have the default behaviour while double clicking, what would be the easiest way to achieve this? Thanks

**Comment by GytisSteis** [comment]
Would be really nice if this functionality was optional, or at least possible to opt out of. I am trying to introduce plotly resampler to my team, but the double-click change is holding me back for the most part. We have been using plotly for 4+ years, so everyone in the team have gotten really comfortable with how default plotly works.

With plotly resampler, whenever i want to reset the graph, i double click out of habit, facepalm myself and go looking for the little home icon in the top right corner 😄

**Comment by stdkoehler** [comment]
I love plotly-resampler! It is invaluable for my work with large timeseries data. I'm really confused about the rationale behind this, though. For me plotly-resampler is a tool to have intelligent downsampling of data. I don't understand why you would change the plotly UX. This is confusing for developers and users of the dashboard. I would really love if you could make this UX change optional.
