### ISSUE TITLE
Flickering while updating one series

### ISSUE THREAD

**Issue by zxweed** [predict-idlab/plotly-resampler#62]
I often have several independently updated series on my charts, so I found that the chart redraws them all when updating only one, causing heavy flickering. Ideally, it would be nice if updating the `hf_data` property caused only that series to be redrawn, without the need to explicitly call `reload_data()`, which cannot determine which series has changed (at most you can add a parameter there that points to the changed series?)

Here is the demo and testcase:
![test](https://user-images.githubusercontent.com/16319433/168899721-bbb88d83-7770-4ad6-b6f5-416a2c12f186.gif)
[dual.resampler.zip](https://github.com/predict-idlab/plotly-resampler/files/8711231/dual.resampler.zip)

**Comment by zxweed** [comment]
I rewrote the same script on vanilla plotly - everything updates correctly there, see testcase: [dual.plotly.zip](https://github.com/predict-idlab/plotly-resampler/files/8711237/dual.plotly.zip)

**Comment by jonasvdd** [comment]
@zxweed, on it! 🔍

**Comment by jonasvdd** [comment]
Thanks for pointing out! 
Should be fixed in the next version (will be released in a couple of hours) 🚀

**Comment by zxweed** [comment]
Thanks, @jonasvdd, it works now - you're the fastest open-source developers I've ever met :)
