### ISSUE TITLE
no support for dict representation of plotly traces

### ISSUE THREAD

**Issue by jvdd** [predict-idlab/plotly-resampler#69]
The following code works in plotly, but does not work when wrapping the constructor with `FigureResampler`.

```py
trace = {
    "type": "scatter",
        #  "x": [1, 2, 3],
    "y": np.arange(5_000),
    "name": "some_trace",  # is not even required
}
fig = go.Figure()  # wrapping this will fail
fig.add_trace(trace)
```

We can support dict representation on 2 places;
1) in the constructor of `AbstractFigureAggregator` (-> not really sure if we want to do this)
2) in the `add_trace` method -> our type hinting indicates that we support dict input, but this is clearly not the case

**Comment by jonasvdd** [comment]
should be fixed with #70
