### ISSUE TITLE
update example notebooks

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/plotly-resampler#83]
Main points:
- [x] add `register_plotly_resampler` / `unregister_plotly_resampler`
  - [x] show `register_plotly_resampler` + `pd.options.plotting.backend` = 'plotly'
- [x] show how `add_traces` can be used
- [x] show how `add_trace` and `add_traces` can be used with dict_input 

**to discuss**: maybe also add the hack that when the trace type is not specified with a dict input, that we assume a scatter**gl** will be used; instead of the default scatter behavior.

**Comment by someshfengde** [comment]
Hi I'd like to contribute on this can you please provide more details about where should I add these?

**Comment by jonasvdd** [comment]
Hi, @someshfengde, would be lovely! 

Sure, you could start with 
1. adjusting the `basic_example.ipynb` 
  There, you could
   * add **composability** section: where we highlight how to change the FigureResampler <-> FigureWidgetResampler
   * addjust some traces into dicts 
   * maybe use the add_traces function
2. Adding a new `register_plotly_resampler.ipynb`
   * Where you use the `register_plotly_resampler` function together with the pandas plotly back-end to visualize some series
   * Also highlight the `unsregister...` function + additional keyword arguments that can be fed to this function (e.g., default_n_shown_samples, default_downsampler)

**Comment by jonasvdd** [comment]
Done as #104 is merged!
