### ISSUE TITLE
No module named _lzma 

### ISSUE THREAD

**Issue by someshfengde** [predict-idlab/plotly-resampler#86]
While running the dash_app.py demo I am getting this error 
![image](https://user-images.githubusercontent.com/42097653/175983507-73dce727-1ecd-4c10-8861-cd27371a52fc.png)
I've installed required libraries (dash_bootstrap_components) and some other one's not sure why it's happening 
the code requires lzma for importing `from functional import seq`

**Comment by someshfengde** [comment]
I'll try it again by opening another codespaces (I've tried that with codespaces might be some issue with codespaces)

**Comment by someshfengde** [comment]
Hi, there is an issue with running plotly-resampler in GitHub codespaces. 
It's working fine in the local environment.

**Comment by jvdd** [comment]
Interesting! I'll look into why code spaces won't work (I have never used that environment before though)

**Comment by someshfengde** [comment]
sure :)

**Comment by jvdd** [comment]
I looked into it on the computer of a colleague and stumbled upon the same issue (as I have no access to codespaces atm). 

I might look into in the future when codespaces is publically available (but for now I'll leave it as is)

**Comment by someshfengde** [comment]
Sure 👍🏻
