### ISSUE TITLE
Current LTTB (lttbc) algorithm is sometimes numerically unstable

### ISSUE THREAD

**Issue by jvdd** [predict-idlab/plotly-resampler#93]
There appears to be (very minor) changes in floating point numbers when using the [lttbc](https://github.com/dgoeries/lttbc) LTTB implementation

This causes test `test_fwr_time_based_data_s` to fail sometimes

A fix for this would be using our own lttb algorithm (also implemented in C) -> see #84 

As for now, we will disable this test (as this only occurs in very niche use-cases) and leave this issue open until this problem is resolved (by merging #84)

**Comment by jonasvdd** [comment]
Will be fixed in a new release with #84
