### ISSUE TITLE
Missing points

### ISSUE THREAD

**Issue by AhmedThahir** [predict-idlab/plotly-resampler#99]
Why are points missing?
From the watching the gif linked from your research paper, I thought that it would resample once again when I zoom in.

# Code for the data

```python
from plotly_resampler import FigureResampler
x = np.arange(10_000)
noisy_sin = (3 + np.sin(x / 200) + np.random.randn(len(x)) / 10) * x / 1_000
```

# Before Zooming

### Not Resampled
![image](https://user-images.githubusercontent.com/94914628/178149982-421676d8-6e6a-4dc6-b9f4-d7f63bc06fc4.png)

### Resampled
![image](https://user-images.githubusercontent.com/94914628/178149990-05ee9aea-c7a0-4e17-825f-b8cd798f56c4.png)

# After Zooming
### Not Resampled
![image](https://user-images.githubusercontent.com/94914628/178150060-30c21309-7db1-436f-8325-ad3d5c8d3ec0.png)

### Resampled
![image](https://user-images.githubusercontent.com/94914628/178150075-7a306959-5e7a-429d-8a2f-0a019fe6236e.png)

**Comment by jonasvdd** [comment]
@AhmedThahir As you've closed this issue I suppose you found in the readme/docs that the "show" method returns a static figure whereas the "show_dash" method (for the FigureResampler) enables this interactive resampling

**Comment by AhmedThahir** [comment]
What's the difference between
- using `show_dash` with `FigureResampler` 
- using `show` with `FigureWidgetResampler`

**Comment by jonasvdd** [comment]
Hi @AhmedThahir,

I agree this is somewhat confusing, I think this can be best summarized with:
* `show` *always* returns a static figure view i.e., no dynamic aggregation will be performed
* To have dynamic aggregation:
  * with `FigureResampler`, you need to call `show_dash` -> which spawns a dash-web app, and the dynamic aggregation is realized with dash callback
  * with `FigureWidgetResampler`, you need to use `IPython.display`, which uses widget-events to realize dynamic aggregation.

Did you find our docs confusing? If so, where would you like to get more of this information? Together we can further improve this toolkit 😄

**Comment by AhmedThahir** [comment]
Ah got it now.

Regarding the documentation, I believe it's pretty good. Only that this particular concept that you just clarified wasn't very clear.

If you could add this to an FAQ section or something, it'd be great.

**Comment by jvdd** [comment]
Great suggestion about the FAQ, I'm very keen on adding this. What do you think @jonasvdd?

**Comment by jonasvdd** [comment]
Agree, we can add an FAQ tab to the docs, but would create a separate PR for that!

**Comment by jonasvdd** [comment]
@AhmedThahir,

Now there is an FAQ section in our docs. (https://predict-idlab.github.io/plotly-resampler/FAQ.html
This issue is documented there aswell!
